print("Este programa resuelve la siguiente expresión algortítmica:")
print(" ")
print("a^3(b^2-2ac)")
print("------------")
print("    2b")
print(" ")
a=float(input("Digite el valor de a: "))
b=float(input("Digite el valor de b: "))
c=float(input("Digite el valor de c: "))
resultado=(a**3*(b**2-2*a*c))/(2*b)
print(f"El resultado es {resultado}")